version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      # Optional: Überschreiben Sie Umgebungsvariablen hier, falls nötig
      NODE_ENV: development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: jw-manager

volumes:
  data:
  node_modules:
  # pgdata:
