version: '3.8'

services:
  jwmanager:
    image: ghcr.io/jannih/jwmanager:latest
    ports:
      - '3000:3000'
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NODE_ENV: production
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: jw-manager

volumes:
  data:
