name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/jannih/jwmanager:${{ github.sha }}

      - name: Tag Docker image as latest
        run: docker tag ghcr.io/jannih/jwmanager:${{ github.sha }} ghcr.io/jannih/jwmanager:latest

      - name: Push latest Docker image
        run: docker push ghcr.io/jannih/jwmanager:latest
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
